# What is a function?

It is a piece of reusable code, that aims at solving a particular task.
So, you can call a function instead of writting code by yourself.

Examples:

type() - returns type of a value

Suppose you have a list with the age of students in your class.
You can get the maximum of that list using the function max()

In [ ]:
student_age = [20,25,24,27,37,28,32]
max(student_age)

37

We can assign a variable to the oldest student

In [ ]:
oldest = max(student_age)
print(oldest)

37


In [ ]:
# Another exaple of a built-in function

round(5.879, 2)

# This function takes 2 inputs:
# input 1: value
# input 2: decimal values to round

#Note: inputs are also called arguments in python
# The result of that the function produces is called an output

5.88

In [ ]:
# If you don't specify the input2, python assumes to round to number to the closest integer.
round(5.879)

6

## Help function

To understand, why it works like that we can open the documentation function: help.

Another way of using help, is by using the ? sign before the function.
Like: ?round

In [ ]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [9]:
?round

# What is a method?

A method is a function that belongs to an object.
Everyhting in python is an object, but there are different types of objects.

Examples of objects:
* Strings
* Integers / Floats
* Boolean
* Lists

### List methods: examples

Let's see an example of a method associated to a list object.

In [10]:
student_age.index(24) # gives the index of the element "24" in the list
student_age.count(32) # counts number of times that en elements occurs in a list

2

In [17]:
student_age.append(26)
student_age # check it is updated

[20, 25, 24, 27, 37, 28, 32, 26, 26]

### String methods: examples

In [13]:
name = "ana"

In [14]:
name.capitalize()

'Ana'

In [15]:
name.replace("n", "nn")

'anna'

## How to know which functions exist?
Loof for it frist on:
* Google search
* ChatGPT

# Packages

Python has so many functions and methods that the number of scrips becomes messy!

For managing this, the concept of packaging was created.

You can think of packages as a directoty of python scrips. Each script is a module, which specifies funtions, methods and new python types aimed at solving particular problems.

From the thousands of packages available, some of the most wisely used in data science:

* NumPy: to offically work with arrays
* Matplotlib: for data visualization
* scikit-learn: for machine learning


### Install packages

Google Collab already has the packages we need installed.

On your computer system you can use *pip*, a python maintenance system too install them on your computer system.

1. Go to https://pip.pypa.io/en/stable/installation/

2. Download get-pip.py

3. On your terminal:

    $ python3 get-pip.py

    $ python3 install numpy

### Import packages



In [21]:
import numpy

If we try to generate an array like this is gives an error:

In [22]:
array([1,2,3])

NameError: ignored

Numpy arrays take a list as input.
Array is a method contained in the NumPy package.

In [23]:
numpy.array([1,2,3])

array([1, 2, 3])

Writting numpy every time can become super tireing! That's why usually programmers use the following:

In [25]:
import numpy as np

In [27]:
np.array([7,10])

array([ 7, 10])

You can also import a specific function from numpy

In [28]:
from numpy import array